export enum ActionType {
    SPINNER = 'SPINNER',
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    INCREMENT_CART = 'INCREMENT_CART',
    DECREMENT_CART = 'DECREMENT_CART',
    CART_POST = 'CART_POST',
    GET_CART = 'GET_CART',
    CLEAR_CART = 'CLEAR_CART',
}
